Activity/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('activitybase/<int:activitybase_id>/citycallers/add', views.activitybase_citycallers_add, name='city-callers-add'),
    path('citycallers/<int:object_id>', views.citycallers_edit, name='city-callers-edit'),

    path('activitybase/<int:activitybase_id>/mediareferrals/add', views.activitybase_mediareferrals_add, name='media-referrals-add'),
    path('mediareferrals/<int:object_id>', views.mediareferrals_edit, name='media-referrals-edit'),

    path('activitybase/<int:activitybase_id>/event/add', views.activitybase_event_add, name='event-add'),
    path('event/<int:object_id>', views.event_edit, name='event-edit'),

    path('activitybase/<int:activitybase_id>/priceoffer/add', views.activitybase_priceoffer_add, name='price-offer-add'),
    path('priceoffer/<int:object_id>', views.priceoffer_edit, name='price-offer-edit'),

    path('activitybase/<int:activitybase_id>/saleprocess/add', views.activitybase_saleprocess_add, name='sale-process-add'),
    path('saleprocess/<int:object_id>', views.saleprocess_edit, name='sale-process-edit'),
    
    path('activity/add', views.activity_add),
    path('activity/<int:pk>/', views.ActivityDetailView.as_view()),
    path('activity/<int:pk>/edit', views.ActivityUpdate.as_view()),  
]

Checks/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('checks/', views.check_list, name='checks-list'),
    path('checks/add', views.check_add, name='checks-add'),
    path('checks/<int:id>', views.check_edit),
    path('checks/<int:pk>/del', views.PaymentCheckDelete.as_view()),
         
    path('employeechecks/', views.employeecheck_list, name='employee-checks-list'),
    path('employeechecks/add', views.employeecheck_add, name='employee-checks-add'),
    path('employeechecks/<int:id>', views.employeecheck_edit),
    path('employeechecks/<int:id>/del', views.EmployeeCheckDelete.as_view()),
]

NiceHouse/urls.py
from django.contrib import admin, auth
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('analytics/', include('Analytics.urls')),
    path('indices/', include('Indices.urls')),
    path('checks/', include('Checks.urls')),
    path('activities/', include('Activity.urls')),
]

from Management.models import *
from Management.views import *

import Management.export.views as views_export
#import Management.importers.views as views_import

urlpatterns += [
    path('', index),
    path('locatehouse', locate_house),
    path('locatedemand', locate_demand),
    
    path('contacts/', ContactListView.as_view()),
    path('contact/add', ContactCreate.as_view()),
    path('contact/<int:pk>', ContactUpdate.as_view()),
    path('contact/<int:id>/del', contact_delete),

    path('projects/', ProjectListView.as_view()),
    path('projects/pdf', project_list_pdf),
    path('projects/archive', ProjectArchiveListView.as_view()),
    
    path('projects/<int:obj_id>/addreminder', obj_add_reminder,
     {'model':Project}),
    path('projects/<int:obj_id>/reminders', obj_reminders,
     {'model':Project}),
    
    path('projects/<int:obj_id>/attachment/add', obj_add_attachment,
     {'model':Project}),
    path('projects/<int:obj_id>/attachments', obj_attachments,
     {'model':Project}),

    path('projects/<int:project_id>/addcontact', project_contact),
    path('projects/<int:project_id>/contact/<int:id>/remove', project_removecontact),
    path('projects/<int:project_id>/contact/<int:id>/delete', project_deletecontact),
    path('projects/<int:project_id>/demandcontact', project_contact, {'demand':True}),
    path('projects/<int:project_id>/paymentcontact', project_contact, {'payment':True}),
    path('projects/<int:project_id>/contacts/<int:id>/del', contact_delete),
    path('projects/<int:id>/', project_edit, name='project-edit'),
    path('projectcommission/<int:pk>', ProjectCommissionUpdate.as_view()),
    path('projects/add/', project_add),
    path('projects/end/<int:pk>', ProjectEndUpdate.as_view()),
    path('projects/<int:project_id>/buildings', project_buildings),
    path('projects/<int:project_id>/buildings/add', building_add),
    
    path('buildings/<int:pk>', BuildingUpdate.as_view()),
    path('buildings/<int:object_id>/clients/', building_clients),
    path('buildings/<int:object_id>/clients/pdf', building_clients_pdf),
    path('buildings/<int:building_id>/addparking', building_addparking),
    path('buildings/<int:building_id>/addstorage', building_addstorage),
    path('buildings/<int:object_id>/pricelist/type<int:type_id>', building_pricelist),
    path('buildings/<int:building_id>/pricelist/type<int:type_id>/house/<int:house_id>/del', house_delete),
    path('buildings/<int:object_id>/pricelist/type<int:type_id>/pdf', building_pricelist_pdf),
    path('buildings/<int:building_id>/addhouse/type<int:type_id>', building_addhouse),
    path('buildings/<int:building_id>/house/<int:id>/type<int:type_id>', house_edit),
    path('buildings/<int:building_id>/house/<int:id>/type<int:type_id>/versionlog', house_version_log),
    path('buildings/<int:building_id>/copy', building_copy),
    path('buildings/<int:building_id>/del', building_delete),

    path('projects/<int:project_id>/<commission>/', project_commission_add),
    path('projects/<int:project_id>/<commission>/del', project_commission_del),

    path('projects/<int:id>/addinvoice', project_invoice_add),
    path('projects/<int:id>/addpayment', project_payment_add),
    
    path('projects/<int:project_id>/demands/notyetpaid', project_demands, {'demand_type':'not-yet-paid'}),
    path('projects/<int:project_id>/demands/unpaid', project_demands, {'demand_type':'un-paid'}),
    path('projects/<int:project_id>/demands/noinvoice', project_demands, {'demand_type':'no-invoice'}),
    path('projects/<int:project_id>/demands/nopayment', project_demands, {'demand_type':'no-payment'}),
    path('projects/<int:project_id>/demands/mispaid', project_demands, {'demand_type':'mis-paid'}),
    path('demandsall', demands_all),
    
    path('buildings/add', building_add),
     
    path('parkings/<int:pk>', ParkingUpdate.as_view()),
    path('storages/<int:pk>', StorageUpdate.as_view()),
        
    path('employees/<int:obj_id>/attachment/add', obj_add_attachment,
     {'model':Employee}),
    path('employees/<int:obj_id>/attachments', obj_attachments,
     {'model':Employee}),
    path('employees/<int:obj_id>/addreminder', obj_add_reminder,
     {'model':Employee}),
    path('employees/<int:obj_id>/reminders', obj_reminders,
     {'model': Employee}),

    path('employees/<int:object_id>/loans', employee_loans),
    path('employees/<int:object_id>/loans/pdf', employee_loans_pdf, name='employee-loans-pdf'),
    path('employees/<int:object_id>/loans/export', views_export.employee_loans_export, name='employee-loans-export'),
    path('employees/<int:employee_id>/addloan', employee_addloan),
    path('employees/<int:employee_id>/loanpay', employee_loanpay),

    path('employees/<int:employee_id>/<commission>/project/<int:project_id>', employee_commission_add),
    path('employees/<int:employee_id>/<commission>/project/<int:project_id>/del', employee_commission_del),    
    path('employees/<int:employee_id>/addproject', employee_project_add),
    path('employees/<int:employee_id>/removeproject/<int:project_id>', employee_project_remove),
    path('employees/', EmployeeListView.as_view()),
    path('employees/pdf', employee_list_pdf),
    path('employees/archive', EmployeeArchiveListView.as_view()),
    path('employees/add/', EmployeeCreate.as_view()),
    path('employees/<int:pk>/', EmployeeUpdate.as_view()),
    path('employees/end/<int:object_id>', employee_end),
    path('employees/<int:id>/employmentterms', employee_employmentterms,
     {'model':EmployeeBase}),
    path('employees/<int:id>/account', employee_account,
     {'model':EmployeeBase}),

    # NOT USED 
    path('accounts/<int:pk>/', AccountUpdate.as_view()),
     
    path('epcommission/<int:pk>', EPCommissionUpdate.as_view()),

    path('nhemployees/<int:obj_id>/attachment/add', obj_add_attachment,
     {'model':EmployeeBase}),
    path('nhemployees/<int:obj_id>/attachments', obj_attachments,
     {'model':EmployeeBase}),
    path('nhemployees/<int:obj_id>/addreminder', obj_add_reminder,
     {'model':EmployeeBase}),
    path('nhemployees/<int:obj_id>/reminders', obj_reminders,
     {'model': EmployeeBase}),
    path('nhemployees/<int:object_id>/loans', employee_loans),
    path('nhemployees/<int:employee_id>/addloan', nhemployee_addloan),
    path('nhemployees/<int:employee_id>/loanpay', nhemployee_loanpay),
    path('nhemployees/add/', nhemployee_add),
    # NOT USED 
    path('nhemployees/<int:pk>/', NHEmployeeUpdate.as_view()),
    # NOT USED 
    path('nhemployees/end/<int:pk>/', NHEmployeeEndUpdate.as_view()),
    path('nhemployees/<int:id>/employmentterms', employee_employmentterms,
     {'model':EmployeeBase}),
    path('nhemployees/<int:id>/account', employee_account,
     {'model':EmployeeBase}),
     
    path('nhcbi/add', NHCommissionCreate.as_view()),
    path('nhcbi/<int:pk>', NHCommissionUpdate.as_view()),
    path('nhcbi/<int:pk>/del', NHCommissionDelete.as_view()),
          
    path('reminder/<int:pk>', ReminderUpdate.as_view()),
    path('reminder/<int:id>/del', reminder_del),
    path('reminder/<int:id>/do', reminder_do),

    path('attachments', attachment_list),
    path('attachment/add', attachment_add),
    path('attachment/<int:pk>', AttachmentUpdate.as_view()),
    path('attachment/<int:pk>/del', AttachmentDelete.as_view()),
    
    path('nhbranch/add', NHBranchCreate.as_view()),
    path('nhbranch/<int:pk>/', NHBranchUpdate.as_view()),

    path('nhbranch/<int:nhbranch_id>/sales/', nhmonth_sales),
    path('nhmonth/close', nhmonth_close),
    path('nhseasonincome/', nh_season_income),
    
    path('projects/<int:project_id>/signups/', signup_list),
    path('projects/<int:project_id>/signups/add', signup_edit),
    path('signups/<int:id>/cancel', signup_cancel),
    path('signups/<int:id>', signup_edit),
    
    path('sale', sale_add),
    path('sale/<int:id>', sale_edit),
    path('sale/<int:sale_id>/commission', salecommissiondetail_edit),

    path('splitpayment/add', split_payment_add),

    path('salaries/bank/', salaries_bank, name='salary-bank'),

    path('salaries/expenses/', SalaryExpensesListView.as_view(), name='salary-expenses'),
    path('nh-salaries/expenses/', NHSalaryExpensesListView.as_view(), name='nh-salary-expenses'),
    path('salaries/expenses/<int:id>/approve', salary_expenses_approve),
    path('salaries/expenses/<int:pk>', SalaryExpensesUpdate.as_view()),
     path('salary/<int:salary_id>/expenses', employee_salary_expenses),
     
    path('salaries/', employee_salary_list, name='salary-list'),
    path('salaries/calc', employee_salary_calc_month, name='salary-month-calc'),
    path('salaries/export', views_export.employee_salary_export, name='salary-list-export'),
    path('salaries/season/', employeesalary_season_list, name='salary-season'),
    path('salaries/season/export', views_export.employee_salary_season_export, name='salary-season-export'),
    path('salaries/season/total-expenses/', employeesalary_season_total_expenses, name='salary-season-total-expenses'),
    path('salaries/season/total-expenses/export', views_export.employeesalary_season_total_expenses_export, name='salary-season-total-expenses-export'),
    path('salaries/season/expenses/', employeesalary_season_expenses, name='salary-season-expenses'),
    path('salaries/season/expenses/export', views_export.employeesalary_season_expenses_export, name='salary-season-expenses-export'),

    path('salaries/<int:year>/<int:month>/pdf', employee_salary_pdf),
    path('salaries/<int:pk>', EmployeeSalaryUpdate.as_view()),

Activity/models.py
from django.db import models

from django.utils.translation import gettext

from Management.models import Sale, NHSale, Signup, House, Building, Project, Employee, NHEmployee, NHBranch

# Create your models here.
class Media(models.Model):
    name = models.CharField(gettext('name'), max_length=20, unique=True)
        
class City(models.Model):
    name = models.CharField(gettext('name'), max_length=20, unique=True)
        
class CityCallers(models.Model):
    activity_base = models.ForeignKey('ActivityBase', on_delete=models.PROTECT, editable=False)
    
    city = models.ForeignKey('City', on_delete=models.PROTECT, verbose_name = gettext('city'), blank=True)
    callers_num = models.PositiveSmallIntegerField(gettext('callers_num'))

class MediaReferrals(models.Model):
    activity_base = models.ForeignKey('ActivityBase', on_delete=models.PROTECT, editable=False)
    
    media = models.ForeignKey('Media', on_delete=models.PROTECT, verbose_name = gettext('media'), blank=True)
    referrals_num = models.PositiveSmallIntegerField(gettext('referrals_num'))

class PriceOffer(models.Model):
    nhactivity = models.ForeignKey('NHActivity', on_delete=models.PROTECT, editable=False)
    
    nhemployee = models.ForeignKey(NHEmployee, on_delete=models.PROTECT, verbose_name = gettext('nhemployee'))
    
    address = models.CharField(gettext('address'), max_length=50)
    rooms = models.FloatField(gettext('rooms'))
    
    clients = models.CharField(gettext('clients'), max_length=50)
    
    price_wanted = models.IntegerField(gettext('price_wanted'))
    price_offered = models.IntegerField(gettext('price_offered'))
    
    commission_seller = models.FloatField(gettext('commission_seller'))
    commission_buyer = models.FloatField(gettext('commission_buyer'))
    
    remarks = models.TextField(gettext('remarks'), max_length=200, null=True, blank=True)

class SaleProcess(models.Model):
    activity_base = models.ForeignKey('ActivityBase', on_delete=models.PROTECT, editable=False)
    
    project = models.ForeignKey(Project, on_delete=models.PROTECT, verbose_name=gettext('project'))
    building = models.ForeignKey(Building, on_delete=models.PROTECT, verbose_name=gettext('building'))
    house = models.ForeignKey(House, on_delete=models.PROTECT, verbose_name=gettext('house'))
    
    price = models.IntegerField(gettext('price'))
    objection = models.TextField(gettext('objection'), max_length=200, null=True, blank=True)
    remarks = models.TextField(gettext('remarks'), max_length=200, null=True, blank=True)

class Event(models.Model):
    activity_base = models.ForeignKey('ActivityBase', on_delete=models.PROTECT, editable=False)
    
    date = models.DateTimeField(gettext('date'))
    initiator = models.CharField(gettext('event_initiator'), max_length=50)
    subject = models.CharField(gettext('event_subject'), max_length=50)
    attendees = models.TextField(gettext('event_attendees'), max_length=200, null=True, blank=True)
    summary = models.TextField(gettext('event_summary'), max_length=200, null=True, blank=True)
    issues = models.TextField(gettext('issues'), max_length=200, null=True, blank=True)
    remarks = models.TextField(gettext('remarks'), max_length=200, null=True, blank=True)
    
    class Meta:
        ordering = ['date']
    
class ActivityBase(models.Model):
    from_date = models.DateField(gettext('from_date'))
    to_date = models.DateField(gettext('to_date'))
    office_meetings_num = models.PositiveSmallIntegerField(gettext('office_meetings_num'))
    recurring_meetings_num = models.PositiveSmallIntegerField(gettext('recurring_meetings_num'))
    new_meetings_from_phone_num = models.PositiveSmallIntegerField(gettext('new_meetings_from_phone_num'))
    
class Activity(ActivityBase):
    project = models.ForeignKey(Project, on_delete=models.PROTECT, verbose_name=gettext('project'))
    employee = models.ForeignKey(Employee, on_delete=models.PROTECT, verbose_name = gettext('employee'))
    
    @property
    def sales(self):
        return Sale.objects.filter(house__building__project = self.project, employee = self.employee,
                                   sale_date__range = (self.from_date, self.to_date))
    @property
    def signups(self):
        return Signup.objects.filter(house__building__project = self.project, employee = self.employee,
                                     date__range = (self.from_date, self.to_date))
    @property
    def canceled_signups(self):
        return self.signups.filter(cancel__isnull = False)
    @property
    def active_signups(self):
        return self.signups.filter(cancel__isnull = True)
    
    class Meta:
        db_table = 'Activity'
        
class NHActivity(ActivityBase):
    nhbranch = models.ForeignKey(NHBranch, on_delete=models.PROTECT, verbose_name=gettext('nhbranch'))
    nhemployee = models.ForeignKey(NHEmployee, on_delete=models.PROTECT, verbose_name = gettext('nhemployee'))
    
    @property
    def nhsales(self):
        return NHSale.objects.filter(nhsaleside_set__signing_advisor = self.nhemploee)

Management/templates/Activity/activity_detail.html
{% extends "../base.html" %}

{% load static %}
{% load humanize %}

{% block content %}	
	<h3 class="text-center text-danger">דו"ח פעילות לאתר</h3>
	<div id="rightSide">
		<fieldset class="cardFieldset">
			<legend>פרטים כלליים</legend>
			<table cellspacing="2" cellpadding="2" class="formTable">
				<tr>
					<th>פרוייקט</th>
					<td>{{object.project}}</td>
				</tr>
				<tr>
					<th>עובד</th>
					<td>{{object.employee}}</td>
				</tr>
				<tr>
					<th>מתאריך</th>
					<td>{{object.from_date|date:"j/m/y"}}</td>
				</tr>
				<tr>
					<th>עד תאריך</th>
					<td>{{object.to_date|date:"j/m/y"}}</td>
				</tr>
				<tr>
					<th>מס' פגישות במשרד</th>
					<td>{{object.office_meetings_num}}</td>
				</tr>
				<tr>
					<th>מס' פגישות חוזרות</th>
					<td>{{object.recurring_meetings_num}}</td>
				</tr>
				<tr>
					<th>מס' פגישות חדשות מתאום טלפוני</th>
					<td>{{object.new_meetings_from_phone_num}}</td>
				</tr>
				<tr>
					<th></th>
					<td><a href="edit">ערוך</a></td>
				</tr>
			</table>
		</fieldset>
		<fieldset class="cardFieldset" style="float:right; width:45%">
			<legend>כתובות מטלפנים</legend>
			<table class="formTable">
			{% for citycallers in object.citycallers_set.all %}
				<tr>
					<th>{{citycallers.city}}</th>
					<td>{{citycallers.callers_num}}</td>
					<td>
						<a href="{% url 'city-callers-edit' object_id=citycallers.id %}" class="fancybox">
							<i class="fa fa-edit" title='שינוי'></i>
						</a>
					</td>
				</tr>
			{% endfor %}
			</table>
			<a href="{% url 'city-callers-add' activitybase_id=object.id %}" class="fancybox"> 
				<i class="fa fa-fw fa-plus-circle text-success"></i>
			</a>
		</fieldset>
		<fieldset class="cardFieldset" style="float:right; width:45%">
			<legend>מדיה מפנה</legend>
			<table class="formTable">
			{% for mediareferrals in object.mediareferrals_set.all %}
				<tr>
					<th>{{mediareferrals.media}}</th>
					<td>{{mediareferrals.referrals_num}}</td>
					<td>
						<a href="{% url 'media-referrals-edit' object_id=mediareferrals.id %}" class="fancybox">
							<i class="fa fa-edit" title='שינוי'></i>
						</a>
					</td>
				</tr>
			{% endfor %}
			</table>
			<a href="{% url 'media-referrals-add' activitybase_id=object.id %}" class="fancybox"> 
				<i class="fa fa-fw fa-plus-circle text-success"></i>
			</a>
		</fieldset>
	</div>
	<div id="leftSide"> 
		<fieldset class="cardFieldset">
			<legend>הרשמות</legend>
			<table class="formTable">
				<tr>
					<th></th>
					<th>שם הלקוח</th>
					<th>בניין ודירה</th>
					<th>מחיר</th>
					<th>ת. הרשמה</th>
					<th>ת. חוזה צפוי</th>
					<th></th>
				</tr>
			{% for signup in object.active_signups.all %}
				<tr>
					<th>
						<a href="{{signup.get_absolute_url}}">
							<i class="fa fa-edit" title='פרטים'></i>
						</a>
					</th>
					<th>{{signup.clients}}</th>
					<td>{{signup.house}}/{{signup.house.building}}</td>
					<td>{{signup.price|intcomma}}</td>
					<td>{{signup.date|date:"j/m/y"}}</td>
					<td>{{signup.sale_date|date:"j/m/y"}}</td>
					<td><a href="{{signup.get_absolute_url}}/cancel" class="fancybox">בטל</a></td>
				</tr>
			{% endfor %}
			</table>
			<a href="{{object.project.get_absolute_url}}/signups/add" > 
				<i class="fa fa-fw fa-plus-circle text-success"></i>
			</a>
		</fieldset>
		<fieldset class="cardFieldset">
			<legend>הרשמות שבוטלו</legend>
			<table class="formTable">
				<tr>
					<th></th>
					<th>שם הלקוח</th>
					<th>בניין ודירה</th>
					<th>ת. ביטול</th>
					<th>סיבה</th>
				</tr>
			{% for signup in object.canceled_signups.all %}
				<tr>
					<th>
						<a href="{{signup.cancel.get_absolute_url}}" class="fancybox">
							<i class="fa fa-edit" title='פרטים'></i>
						</a>
					</th>
					<th>{{signup.clients}}</th>
					<td>{{signup.house}}/{{signup.house.building}}</td>
					<td>{{signup.price|intcomma}}</td>
					<td>{{signup.cancel.date|date:"j/m/y"}}</td>
					<td>{{signup.cancel.reason}}</td>
				</tr>
			{% endfor %}
			</table>
		</fieldset>
		<fieldset class="cardFieldset">
			<legend>חוזים</legend>
			<table class="formTable">
				<tr>
					<th></th>
					<th>שם הלקוח</th>
					<th>בניין ודירה</th>
					<th>מחיר</th>
					<th>ת. חוזה</th>
				</tr>
			{% for sale in object.sales.all %}
				<tr>
					<th>
						<a href="{{sale.get_absolute_url}}">
							<i class="fa fa-edit" title='פרטים'></i>
						</a>
					</th>
					<th>{{sale.clients}}</th>
					<td>{{sale.house}}/{{signup.house.building}}</td>
					<td>{{sale.price|intcomma}}</td>
					<td>{{sale.date|date:"j/m/y"}}</td>
				</tr>
			{% endfor %}
			</table>
			<a href="/sale"> 
				<i class="fa fa-fw fa-plus-circle text-success"></i>
			</a>
		</fieldset>
		<fieldset class="cardFieldset">
			<legend>רציניים בתהליך</legend>
			<table class="formTable">
				<tr>
					<th></th>
					<th>שם הלקוח</th>
					<th>בניין ודירה</th>
					<th>מחיר</th>
					<th>התנגדויות</th>
					<th>הערות</th>
				</tr>
			{% for saleprocess in object.saleprocess_set.all %}
				<tr>
					<th>
						<a href="{% url 'sale-process-edit' object_id=saleprocess.id %}" class="fancybox">
							<i class="fa fa-edit" title='פרטים'></i>
						</a>
					</th>
					<th>{{saleprocess.clients}}</th>
					<td>{{saleprocess.house}}/{{signup.house.building}}</td>
					<td>{{saleprocess.price|intcomma}}</td>
					<td>{{saleprocess.objection}}</td>
					<td>{{saleprocess.remarks}}</td>
				</tr>
			{% endfor %}
			</table>
			<a href="{% url 'sale-process-add' activitybase_id=object.id %}" class="fancybox"> 
				<i class="fa fa-fw fa-plus-circle text-success"></i>
			</a>
		</fieldset>
		<fieldset class="cardFieldset">
			<legend>אירועים</legend>
			<table class="formTable">
				<tr>
					<th></th>
					<th>תאריך</th>
					<th>יוזם</th>
					<th>נוכחים</th>
					<th>נושא</th>
					<th>סיכום</th>
					<th>נושאים לטיפול</th>
					<th>הערות</th>
				</tr>
			{% for event in object.event_set.all %}
				<tr>
					<th>
						<a href="{% url 'event-edit' object_id=event.id %}" class="fancybox">
							<i class="fa fa-edit" title='פרטים'></i>
						</a>
					</th>
					<th>{{event.date|date:"j/m/y"}}</th>
					<td>{{event.initiator}}</td>
					<td>{{event.attendees}}</td>
					<td>{{event.subject}}</td>
					<td>{{event.summary}}</td>
					<td>{{event.issues}}</td>
					<td>{{event.remarks}}</td>
				</tr>
			{% endfor %}
			</table>
			<a href="{% url 'event-add' activitybase_id=object.id %}" class="fancybox"> 
				<i class="fa fa-fw fa-plus-circle text-success"></i>
			</a>
		</fieldset>
	</div>
	<div class="clearBoth"></div> 
{% endblock content %}

Management/templates/Activity/activity_edit.html
{% extends "../base.html" %}

{% load static %}
{% load humanize %}

{% block scripts %}	
{{ block.super }}
<script>
	var projectSelect;
	var employeeSelect;
	$(document).ready(function() {
		$("input[type!='submit']").attr("class", "inputText");
		$("select").attr("class", "inputText");
		
		projectSelect = $("#id_project");
		employeeSelect = $("#id_employee");
		
		//add click event to projects select : use ajax to get related buildings and employees
		projectSelect.change(onChangeProject);
	});
		
	function onChangeProject()
	{
		$("option", employeeSelect).remove();
		var selectedProject = projectSelect.val();

		$.getJSON("/xml/employees/" + selectedProject, onEmployeeDataArrived);
	}
	
	function onEmployeeDataArrived(data)
	{
		for (i in data)
		{
			obj = data[i];
			text = obj.fields['pid'] + " : " + obj.fields['first_name'] + " " + obj.fields['last_name'];
			employeeSelect.append("<option value='" + obj.pk + "'>" + text + "</option>");
		}
		if (data.length == 1)
			employeeSelect.attr("value", data[0].pk);
	}
</script>
{% endblock scripts %}

{% block content %}	
<h3 class="text-center text-danger">דו"ח פעילות לאתר</h3>
<form method="POST">
	{% csrf_token %}
	<table cellspacing="2" cellpadding="2" class="formTable">
		{% include "Management/form_snippet.html" %}
	<tr>
		<td></td>
		<td>
			<input type="submit" value="אישור" class="button"/>
			<input name="addanother" type="submit" value="אישור והמשך הזנה" class="button"/>
		</td>
	</tr>
</table>
</form>
{% endblock content %}